### ISSUE TITLE
Question - Add _sdc_repository as an identifier for relevant fields?

### ISSUE THREAD

**Issue by ericboucher** [MeltanoLabs/tap-github#22]
Singer's GitHub tap is adding an `_sdc_repository` field for streams that don't get it from the API as an easy-to-use identifier to streams to their parent repo.

See https://github.com/singer-io/tap-github/blob/master/tap_github/__init__.py#L927

Should we do something similar with the Meltano taps?

At the moment, `repo` and `org` keys get added, so we could decide to leverage that instead.

One caveat, some streams actually have fields called `repo` and `org` that could be incompatible (see my upcoming Events stream PR).

**Comment by aaronsteers** [comment]
Hi, @ericboucher. I haven't looked in advance at what the overloaded `repo` and `org` fields would contain in the other stream.

Ideally I'd like to keep `_sdc_` columns to be reserved for a for a specific global set of `Singer Data Capture` metadata columns like those enumerated here: https://sdk.meltano.com/en/latest/implementation/record_metadata.html

Personally, I have considered a generic a `_sdc_parent_keys` column or `sdc_partition_context`, or similar, but I'd like to stay away from the `_sdc_repository` name since that is specifically unique to tap-github.

**Comment by ericboucher** [comment]
This was solved by introducing the repo_id field in #112
