### ISSUE TITLE
Using different API endpoints for a "same" stream

### ISSUE THREAD

**Issue by laurentS** [MeltanoLabs/tap-github#8]
Currently `issue_comments` are fetched from [`/repos/{owner}/{repo}/issues/{issue_number}/comments`](https://docs.github.com/en/rest/reference/issues#get-an-issue-comment) as a child stream of `issues`. This allows fetching only comments for a single issue.

Our use case is more suited to fetching the same data at the repo level, using the [`/repos/{owner}/{repo}/issues/comments`](https://docs.github.com/en/rest/reference/issues#list-issue-comments-for-a-repository) API endpoint. It returns the same data for each comment, according to the docs.

The main value for us in using the second solution is that we get more data for the same API usage quota: the typical issue will have far fewer than 100 comments on it, so we get comments for multiple issues in one call. We do not run this as a child stream, instead we feed it a list of repos for which we want data (as in #5), and sync only this stream. This allows us better control over API usage limits.

Is there a way to have both streams coexist in the tap so that either can be used if needed, but the default setup would not double fetch data? (what I mean is that `issue_comments_by_repo` could be a child stream of `repositories`, and `issue_comments_by_issue` a child of `issues`, itself a child of `repositories`, so if fetching the whole catalog, we would fetch some data twice).

I think there are other streams which have a similar situation, so this is probably a slightly more general question than just this stream (in a similar fashion, `repositories` can be obtained through the `search` endpoint, or the `repos` endpoint, although the data returned is slightly different). Another example is `issue_events` which can be fetch by issue or by repo.

**Comment by aaronsteers** [comment]
@laurentS - I wonder if it's best to just support `issue_comments` in this case as a child of `repo` (driven by the `{repo}/issues/coments` endpoing _instead of_ being a child of `issues`. Performance would be improved, I think, to make a paginated repo-level call, rather than a separate round of calls for each issue, and it would also speak to your points 

 At the time when I was developing the first version of this tap, we were needing an example case to prove parent-child and grandparent-parent-child relationships for the SDK, and for this reason we probably chose a less-than-ideal retrieval path - in the interest of proving the more complex use case.

Given all the above, I think I'd be inclined to take your proposed logic in place of how we have it set now. Wdyt?

**Comment by Ry-DS** [comment]
Was this resolved in #9? We could close then if so :eyes:

**Comment by laurentS** [comment]
Indeed, thanks for pointing it out.
